### ISSUE TITLE
Empty domain for inverse gamma distribution

### ISSUE THREAD

**Issue by Deamonell** [IRIS-Solutions-Team/IRIS-Toolbox#265]
Dear Jaromir,

I have a problem with IRIS version from 20200303 and so on.
I'm trying to estimate a simple QPM model with Bayesian estimation of coefficients.
The "estimate" function gives an error: "Index exceeds the number of array elements (0)".

I've found out that the problem appears since 20200303 and comes from adding a prior on standard deviation (it works with priors on coefficients). The main difference in these priors is that the latter has an inverse gamma prior distribution (while former have beta distribution) and I've found that in the previous version of IRIS it has lower bound and upper bound 0 and inf respectively. However, in 20200303 it has a domain instead. And if in the case of beta distribution it is between 0 and 1, in the case of inverse gamma it is []. 

A simple fix for me that actually works is to change the domain by hands, but I'm not quite sure that I won't break something inside the other part of the code with this action. Maybe you can give me advice on whether my solution is ok and fix the issue in the further version of IRIS.

Thank you for your attention!
Dmytro

**Comment by jaromir-benes** [comment]
Hi Dmytro

the domain for the inv gamma distribution was fixed recently, and it is now
set to [0, Inf] in the latest release, see e.g.

https://github.com/IRIS-Solutions-Team/IRIS-Toolbox/blob/Release-20200626/Statistics/+distribution/InvGamma.m

Best
Jaromir

**Comment by Deamonell** [comment]
Oh, ye, I somehow missed the latest release and used 20200526, where the bug still exists.
Sorry for my inattentiveness. 
Thank you for such a fast answer!

**Comment by jaromir-benes** [comment]
No worries. Best, Jaromir
